CREATE TABLE IF NOT EXISTS nhl_data.players (
    playerId INT PRIMARY KEY,
    isActive BOOLEAN,
    currentTeamId INT,
    currentTeamAbbrev VARCHAR(10),
    teamLogo VARCHAR(100),
    sweaterNumber INT,
    position VARCHAR(5),
    headshot VARCHAR(100),
    heroImage VARCHAR(100),
    heightInInches INT,
    heightInCentimeters INT,
    weightInPounds INT,
    weightInKilograms INT,
    birthDate VARCHAR(10),
    birthCountry VARCHAR(10),
    shootsCatches VARCHAR(5),
    playerSlug VARCHAR(100),
    inTop100AllTime INT,
    inHHOF INT,
)